name: bitcoin_ticker
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.1.0   # Pour les requêtes API (utile dans une app comme Bitcoin Ticker)
  flutter_spinkit: ^5.2.0  # Pour les animations de chargement

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # Bonnes pratiques de codage

flutter:
  uses-material-design: true
